# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Workspace/FPGA/Alinx_Template/PL/Template.srcs/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/FPGA/Alinx_Template/PL/Template.gen/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Workspace/FPGA/Alinx_Template/PL/Template.gen/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Workspace/FPGA/Alinx_Template/PL/Template.srcs/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/FPGA/Alinx_Template/PL/Template.gen/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Workspace/FPGA/Alinx_Template/PL/Template.gen/sources_1/bd/ZYNQ_PS_Design/ip/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0/ZYNQ_PS_Design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_PS_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
